set(polynomials_SOURCES
  lagrangecoeff10.cc
  lagrangecoeff13.cc
  lagrangecoeff16.cc
  lagrangecoeff19.cc
  lagrangecoeff2.cc
  lagrangecoeff5.cc
  lagrangecoeff8.cc
  lagrangecoeff11.cc
  lagrangecoeff14.cc
  lagrangecoeff17.cc
  lagrangecoeff1.cc
  lagrangecoeff3.cc
  lagrangecoeff6.cc
  lagrangecoeff9.cc
  lagrangecoeff12.cc
  lagrangecoeff15.cc
  lagrangecoeff18.cc
  lagrangecoeff20.cc
  lagrangecoeff4.cc
  lagrangecoeff7.cc
  lagrangecoeff.cc
  polycoeff.cc
  lagrangepolynomial.cc
  legansatzpolynomial.cc)

set(polynomials_PUBLIC_HEADERS 
  polycoeff.h
  lagrangecoeff.h
  lagrangepolynomial.h
  )
