set(gmg_SOURCES
  gmg_level.cc
  gmg_level_impl.h
  data_transfer.cc
  dof_identification.cc
  vector_transfer.cc
  level_connection.cc
  basic_hierarchy.cc
  gmg_hierarchy.cc
  gmg_interpolation.cc
  gmg_restriction.cc
  gmg.cc
)

set(gmg_PUBLIC_HEADERS
  util.h
  hybrid_map.h
  gmg_level.h
  data_transfer.h
  dof_identification.h
  vector_transfer.h
  level_connection.h
  basic_hierarchy.h
  gmg_hierarchy.h
  gmg_interpolation.h
  gmg_restriction.h
  gmg.h
)